# Generated by Django 3.0.5 on 2020-09-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adeverinte', '0002_auto_20200902_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
