# Generated by Django 3.0.5 on 2020-09-04 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('date_hire', models.DateField(default=django.utils.timezone.now)),
                ('data_fired', models.DateField()),
                ('type_of_employment', models.TextField()),
                ('total_cost', models.IntegerField()),
                ('net_income', models.IntegerField()),
                ('brut_income', models.IntegerField()),
                ('function', models.TextField()),
                ('sediu', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
